# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build-raspbian-image:
    machine:
      image: circleci/classic:latest

    working_directory: ~/

    steps:
      - run:
          name: "Create a Raspberry Pi custom image with SCALP"
          command: |
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            sudo add-apt-repository universe
            sudo apt-get update
            sudo apt install zip unzip
            sudo apt-get install jq
            sudo apt-get install -y nodejs

            npm install -g github-release-cli

            # Base raspbian image with extra packages installed to run SCALP
            wget https://www.dropbox.com/s/1fsplxwzx71ufox/raspbian_small_backup.img?dl=0
            mv raspbian_small_backup.img?dl=0 raspbian.img
            sudo fdisk -l raspbian.img

            sudo mkdir -p /mnt/image/boot
            sudo mkdir -p /mnt/image/root

            # https://learnaddict.com/2016/02/23/modifying-a-raspberry-pi-raspbian-image-on-linux/
            sudo mount -v -o offset=4194304 -t vfat raspbian.img /mnt/image/boot
            sudo mount -v -o offset=50331648 -t ext4 raspbian.img /mnt/image/root

            cd /mnt/image/root/home/pi/

            sudo rm -rf SCALPScripts
            sudo rm -rf Enamel
            sudo git clone https://github.com/PiETLab/SCALPScripts
            sudo mv SCALPScripts/SCALP.sh SCALPScripts/startSCALP.sh SCALPScripts/unmountDrive.sh SCALPScripts/changeconfig.sh SCALPScripts/config.txt .
            sudo mv SCALPScripts/enamel.desktop .config/autostart/
            sudo mv SCALPScripts/enamel_usb_autostart.rules /mnt/image/root/etc/udev/rules.d/

            spruce_type=SCALP
            sudo wget $(curl -s https://api.github.com/repos/PiETLab/TreasureBoxBrailleApps/releases/latest | jq -r ".assets[] | select(.name | test(\"${spruce_type}\")) | .browser_download_url")
            sudo unzip SCALP.zip
            sudo rm -rf SCALP.zip

            cd ~/

            sudo umount /mnt/image/boot
            sudo umount /mnt/image/root

            CIRCLE_TAG=Release-$(date '+%Y-%m-%d-%H-%M-%S')
            CIRCLE_PROJECT_REPONAME=SCALPScripts
            RASPBERRY_RELEASE_FILE=RASPBERRY-RELEASE-IMAGE

            zip -r raspbian.zip ./raspbian.img
            # The image has a total size of 3GB, so we will split it in 2 files (Github has a 2GB limitation per file)
            zip raspbian.zip --out ${RASPBERRY_RELEASE_FILE}.zip -s 1500m

            echo $(ls -l)

            github-release upload --token ${GITHUB_TOKEN} --owner ${CIRCLE_PROJECT_USERNAME} --repo ${CIRCLE_PROJECT_REPONAME} --tag ${CIRCLE_TAG} --name ${CIRCLE_TAG} --body "Release date: ${now}" ${RASPBERRY_RELEASE_FILE}.z*

workflows:
  version: 2
  build:
    jobs:
      - build-raspbian-image:
          filters:
            branches:
              only: master
